const googleTranslateApi = require('google-translate-api')

module.exports = {
  name: 'google',
  options: {},
  langs: [
    {name: '自动检测', code: 'auto'},
    {name: '南非荷兰语', code: 'af'},
    {name: '阿尔巴尼亚语', code: 'sq'},
    {name: '阿姆哈拉语', code: 'am'},
    {name: '阿拉伯语', code: 'ar'},
    {name: '亚美尼亚语', code: 'hy'},
    {name: '阿塞拜疆语', code: 'az'},
    {name: '巴斯克语', code: 'eu'},
    {name: '白俄罗斯语', code: 'be'},
    {name: '孟加拉语', code: 'bn'},
    {name: '波斯尼亚语', code: 'bs'},
    {name: '保加利亚语', code: 'bg'},
    {name: '加泰罗尼亚语', code: 'ca'},
    {name: '宿霧語', code: 'ceb'},
    {name: '简体中文', code: 'ZH-CN'},
    {name: '繁体中文', code: 'ZH-TW'},
    {name: '科西嘉语', code: 'co'},
    {name: '克罗地亚语', code: 'hr'},
    {name: '捷克语', code: 'cs'},
    {name: '丹麦语', code: 'da'},
    {name: '荷兰语', code: 'nl'},
    {name: '英语', code: 'en'},
    {name: '世界语', code: 'eo'},
    {name: '爱沙尼亚语', code: 'et'},
    {name: '芬兰语', code: 'fi'},
    {name: '法语', code: 'fr'},
    {name: '弗里斯兰语', code: 'fy'},
    {name: '加利西亚语', code: 'gl'},
    {name: '格鲁吉亚语', code: 'ka'},
    {name: '德语', code: 'de'},
    {name: '希腊语', code: 'el'},
    {name: '古吉拉特语', code: 'gu'},
    {name: '海地克里奥尔语', code: 'ht'},
    {name: '豪萨语', code: 'ha'},
    {name: '夏威夷语', code: 'haw'},
    {name: '希伯来语', code: 'iw'},
    {name: '印地语', code: 'hi'},
    {name: '苗语', code: 'hmn'},
    {name: '匈牙利语', code: 'hu'},
    {name: '冰岛语', code: 'is'},
    {name: '伊博语', code: 'ig'},
    {name: '印度尼西亚语', code: 'id'},
    {name: '爱尔兰语', code: 'ga'},
    {name: '意大利语', code: 'it'},
    {name: '日语', code: 'ja'},
    {name: '爪哇语', code: 'jw'},
    {name: '卡纳达语', code: 'kn'},
    {name: '哈萨克语', code: 'kk'},
    {name: '高棉语', code: 'km'},
    {name: '朝鲜语', code: 'ko'},
    {name: '库尔德语', code: 'ku'},
    {name: '吉尔吉斯语', code: 'ky'},
    {name: '老挝语', code: 'lo'},
    {name: '拉丁语', code: 'la'},
    {name: '拉脱维亚语', code: 'lv'},
    {name: '立陶宛语', code: 'lt'},
    {name: '卢森堡语', code: 'lb'},
    {name: '马其顿语', code: 'mk'},
    {name: '马尔加什语', code: 'mg'},
    {name: '马来语', code: 'ms'},
    {name: '马拉雅拉姆语', code: 'ml'},
    {name: '毛利语', code: 'mi'},
    {name: '马拉语', code: 'mr'},
    {name: '蒙古语', code: 'mn'},
    {name: '缅甸语', code: 'my'},
    {name: '尼泊尔语', code: 'ne'},
    {name: '挪威语', code: 'no'},
    {name: '奇切瓦语', code: 'ny'},
    {name: '普什图语', code: 'ps'},
    {name: '波斯语', code: 'fa'},
    {name: '波兰语', code: 'pl'},
    {name: '葡萄牙语', code: 'pt'},
    {name: '旁遮普语', code: 'pa'},
    {name: '罗马尼亚语', code: 'ro'},
    {name: '俄语', code: 'ru'},
    {name: '萨摩亚语', code: 'sm'},
    {name: '苏格兰盖尔语', code: 'gd'},
    {name: '塞尔维亚语', code: 'sr'},
    {name: '塞索托语', code: 'st'},
    {name: '绍纳语', code: 'sn'},
    {name: '信德语', code: 'sd'},
    {name: '僧伽罗语', code: 'si'},
    {name: '斯洛伐克语', code: 'sk'},
    {name: '斯洛文尼亚语', code: 'sl'},
    {name: '索马里语', code: 'so'},
    {name: '西班牙语', code: 'es'},
    {name: '巽语', code: 'su'},
    {name: '斯瓦希里语', code: 'sw'},
    {name: '瑞典语', code: 'sv'},
    {name: '他加禄语', code: 'tl'},
    {name: '塔吉克语', code: 'tg'},
    {name: '泰米尔语', code: 'ta'},
    {name: '泰卢固语', code: 'te'},
    {name: '泰语', code: 'th'},
    {name: '土耳其语', code: 'tr'},
    {name: '乌克兰语', code: 'uk'},
    {name: '乌尔都语', code: 'ur'},
    {name: '乌兹别克语', code: 'uz'},
    {name: '越南语', code: 'vi'},
    {name: '威尔士语', code: 'cy'},
    {name: '科萨语', code: 'xh'},
    {name: '意第绪语', code: 'yi'},
    {name: '约鲁巴语', code: 'yo'},
    {name: '祖鲁语', code: 'zu'}
  ],
  run: function (text, cb) {
    googleTranslateApi(text, {
      from: this.options.from,
      to: this.options.to
    }).then(res => {
      cb(null, res.text)
    }).catch(err => {
      cb(err)
    })
  }
}
