osx_image: xcode8.3

dist: trusty
sudo: false

language: node_js
node_js:
  - "node"

matrix:
  include:
    - os: osx
    - os: linux

cache:
  directories:
    - node_modules

install:
  - npm uninstall hexo --save
  - npm install
  - npm install hexo --save

script:
  - npm run build

branches:
  only:
    - master